version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: shop_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
      TZ: Asia/Taipei
    ports:
      - "3307:3306"
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--skip-character-set-client-handshake"
      ]
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: shop_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
